-- script: default lua script executed by nextspider, script should be located in the relative path of this folder
-- if you want to execute a lua script which is in the absolute path, you can use -s option in the command line
--script = "default.lua"
-- cookies: with cookies nextspider can access url with logging and more features
--cookies = "username=qianngchn; password=0123456789;"
-- proxy: proxy setting used by nextspider
--proxy = "http://127.0.0.1:7777"
-- check_mode: check whether lua script executes correctly, without downloading any file
--check_mode = false
-- quiet: whether to write output to stdout
--quiet = false
-- logger: whether to write output to stat.log in this folder
--logger = false
